openapi: 3.0.1
info:
  title: Pets API
  version: 1.0.0
  description: >
    Documentation for the **Pets** module of the Final Project.
    Includes CRUD operations for pets.

tags:
  - name: Pets
    description: Endpoints for the pets module

paths:
  /api/v1/pets:
    get:
      summary: Get all pets
      tags: [Pets]
      responses:
        "200":
          description: List of pets obtained successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Pet"
        "500":
          description: Internal server error

    post:
      summary: Create a new pet
      tags: [Pets]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PetInput"
      responses:
        "201":
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        "400":
          description: Bad request

  /api/v1/pets/{id}:
    get:
      summary: Get a pet by ID
      tags: [Pets]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The pet ID
      responses:
        "200":
          description: Pet obtained successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        "404":
          description: Pet not found
        "500":
          description: Internal server error

    put:
      summary: Update a pet
      tags: [Pets]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The pet ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PetInput"
      responses:
        "200":
          description: Pet updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        "400":
          description: Bad request
        "404":
          description: Pet not found

    delete:
      summary: Delete a pet
      tags: [Pets]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The pet ID
      responses:
        "200":
          description: Pet deleted successfully
        "404":
          description: Pet not found
        "500":
          description: Internal server error

components:
  schemas:
    Pet:
      type: object
      properties:
        _id:
          type: string
          example: 670fbc03df69b944d843e7a2
        name:
          type: string
          example: Fido
        specie:
          type: string
          example: Dog
        age:
          type: number
          example: 3
        adopted:
          type: boolean
          example: false
        owner:
          type: string
          example: 670fbc03df69b944d843e7a1
    PetInput:
      type: object
      properties:
        name:
          type: string
          example: Fido
        specie:
          type: string
          example: Dog
        age:
          type: number
          example: 3
